In [5]:
import numpy as np

In [9]:
# Create an array of 15 equally spaced float numbers from 0 to 10
arr = np.linspace(0, 10, 15)
arr

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
# Define the four arrays
arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

# Combine them into a 3D array with shape (2, 2, 3)
array_3d = np.array([
    [arr1, arr2],
    [arr3, arr4]
])
array_3d

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

In [43]:
# Print the array's type, data type, shape, total number of elements, and number of dimensions
print('Array Type is:', type(array_3d))
print('Data Type is:', array_3d.dtype)
print('Shape is:', array_3d.shape)
print('Total number of elements is:', array_3d.size)
print('Number of dimensions is:', array_3d.ndim)

Array Type is: <class 'numpy.ndarray'>
Data Type is: float64
Shape is: (2, 2, 3)
Total number of elements is: 12
Number of dimensions is: 3


In [45]:
# Convert to 4D by adding a new axis
array_4d = array_3d[np.newaxis, :]
array_4d

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

In [47]:
# Print shape and number of dimensions
print("Shape is :", array_4d.shape)
print("Number of dimensions is :", array_4d.ndim)

Shape is : (1, 2, 2, 3)
Number of dimensions is : 4


In [51]:
# Convert the data type to integer
array_int = array_4d.astype(int)

# Print the new array
array_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [56]:
# Iterate through all elements using nditer
for x in np.nditer(array_int):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [70]:
# Print the 8th element (remember: Python uses 0-based indexing)
print("Element 8:", array_int.flat[7])

Element 8: 8


In [74]:
# Print the 5th and 6th elements
print("Element 5 and 6:", array_int.flat[4], array_int.flat[5])

Element 5 and 6: 5 6


In [76]:
# Search for the value 8 in the array
result = np.where(array_int == 8)
print("Index of element 8:", result)

Index of element 8: (array([0]), array([1]), array([0]), array([1]))


In [78]:
# Create a new array with the desired shape (2, 3, 2)
reshaped_array = np.array([
    [[1, 2],
     [3, 4],
     [5, 6]],

    [[7, 8],
     [9, 10],
     [11, 12]]
])

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [80]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

# Merge arrays along the default axis (axis=0)
merged_default = np.concatenate((arr1, arr2))
print("Merged without specifying axis (default axis=0):\n", merged_default)

Merged without specifying axis (default axis=0):
 [['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


In [82]:
# Merge arrays horizontally (along axis=1)
merged_axis1 = np.concatenate((arr1, arr2), axis=1)
print("Merged along axis=1:\n", merged_axis1)

Merged along axis=1:
 [['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


In [86]:
# Split the merged array horizontally into two arrays
split1, split2 = np.split(merged_axis1, 2, axis=1)

print("First split array:\n", split1)
print("Second split array:\n", split2)

First split array:
 [['A' 'B']
 ['E' 'F']]
Second split array:
 [['C' 'D']
 ['G' 'H']]
